server:
  port: 8081

management:
  server:
    port: 9081
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active:
      - ${ACTIVE_SPRING_PROFILE:local}
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true
    locations: classpath:/db/migration
    validate-on-migrate: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:${eric.work-dir}/h2/auth;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=MySQL;DATABASE_TO_UPPER=FALSE
    username: root
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
  config: classpath:${SPRING_CONFIG_FILE:logback-spring.xml}
  level:
    org.springframework.security: TRACE

eric:
  work-dir: ${user.home}/.eric-dev